dataset: 'cifar10'
noise_mode: 'symmetric'
noise_rate: 0.1
path: 'noisy_label_generation/labels'

batch_size: 32
epochs: 300
sigma: 0.0
learning_rate: 0.001
momentum: 0.9
weight_decay: 0.0005

cifar10:
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

cifar100:
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]

save_every_kth_epoch: 5
checkpoint_path: "../model"
